import { useMemo, useState } from 'react'
import { ClassTypeDescription } from '@gbtt/shared/studio/ClassTypeDescription'
import { AppChrome } from '../../components/AppChrome'
import { WeekSessionCalendar } from '../../components/WeekSessionCalendar'
import { useLiveSessions, useWeeklyLocks } from '../../hooks/useLiveSessions'
import {
  studioBookSession,
  studioLockWeeklySlot,
  studioUnlockWeeklySlot,
  type DropInPrompt,
} from '@gbtt/shared/studio/studioAuth'
import {
  DEMO_ACTIVATION_KEY,
  formEndpointConfigured,
  requestActivationEmail,
} from '@gbtt/shared/studio/accountApi'
import {
  FITNESS_PLANS,
  acceptTerms,
  bookAsGuest,
  bookAsMember,
  classTypeById,
  dropMemberBooking,
  formatSessionAttending,
  formatPrepaid,
  getOccurrences,
  getSessionUser,
  getSiteContent,
  login,
  logout,
  occurrenceById,
  occurrencesByWeekday,
  planById,
  registerMember,
  requestSubscriptionChange,
  reshuffleBooking,
  sessionExercises,
  setShowNameToClassmates,
  spotsLeft,
  syncLabels,
  visibleRosterNames,
  type ClassOccurrence,
  type PlanId,
} from '../../shared/fitnessStudio'

/**
 * Member booking — Mon–Fri calendar grid, login underneath, select / reshuffle sessions.
 */
export default function StudioFlow() {
  const [tick, setTick] = useState(0)
  const refresh = () => setTick((n) => n + 1)

  const [selectedId, setSelectedId] = useState<string | null>(null)
  const [authEmail, setAuthEmail] = useState('alex@demo')
  const [authPassword, setAuthPassword] = useState('demo')
  const [regName, setRegName] = useState('')
  const [regEmail, setRegEmail] = useState('')
  const [regPlan, setRegPlan] = useState<PlanId>('weekly2')
  const [regActivationKey, setRegActivationKey] = useState('')
  const [activationEmailSent, setActivationEmailSent] = useState(false)
  const [showRegister, setShowRegister] = useState(false)
  const [guestName, setGuestName] = useState('')
  const [guestEmail, setGuestEmail] = useState('')
  const [reshuffleFrom, setReshuffleFrom] = useState<string | null>(null)
  const [message, setMessage] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)

  const user = getSessionUser()
  const member = user?.role === 'member' ? user : null
  const site = getSiteContent()
  // Firestore is authoritative for availability; the seeded store is only a
  // development fallback so members are never shown an invented spot count.
  const live = useLiveSessions()
  const usingLive = live.status !== 'unavailable'
  const lockedSlotIds = useWeeklyLocks(usingLive && !!member)
  const localByDay = useMemo(() => occurrencesByWeekday(), [tick])
  const byDay = usingLive ? live.byDay : localByDay
  const sync = useMemo(() => syncLabels(), [tick])
  const selected = selectedId
    ? usingLive
      ? live.occurrences.find((o) => o.id === selectedId)
      : occurrenceById(selectedId)
    : undefined
  const selectedType = selected ? classTypeById(selected.classTypeId) : undefined
  const [busy, setBusy] = useState(false)
  const [dropIn, setDropIn] = useState<{ prompt: DropInPrompt; occ: ClassOccurrence } | null>(null)

  const formatMoney = (cents: number) => `$${(cents / 100).toFixed(2)}`

  /** Readable label for a locked slot id, from any session generated by that slot. */
  const slotLabel = (slotId: string) => {
    const occ = live.occurrences.find((o) => o.slotId === slotId)
    if (!occ) return slotId
    return `${classTypeById(occ.classTypeId)?.name ?? occ.classTypeId} · ${occ.dayLabel} ${occ.time}`
  }

  // A lock is stored against the recurring slot, so every session generated
  // from that slot shows as held.
  const heldIds = usingLive
    ? live.occurrences.filter((o) => o.slotId && lockedSlotIds.includes(o.slotId)).map((o) => o.id)
    : (member?.weeklyLockedOccurrenceIds ?? [])
  const selectedIsLocked = selected ? heldIds.includes(selected.id) : false

  const flash = (ok: string | null, err: string | null) => {
    setMessage(ok)
    setError(err)
    refresh()
  }

  const lockSlot = async (slotId: string | undefined, occurrenceId: string) => {
    if (!usingLive) {
      const err = bookAsMember(occurrenceId)
      flash(err ? null : 'Weekly slot locked — repeats every week.', err)
      return
    }
    if (!slotId) {
      flash(null, 'This session is not part of a recurring slot, so it cannot be locked weekly.')
      return
    }
    setBusy(true)
    const { error: err, booked, full } = await studioLockWeeklySlot(slotId)
    setBusy(false)
    flash(
      err
        ? null
        : `Weekly slot locked — ${booked} upcoming session${booked === 1 ? '' : 's'} booked` +
          (full ? `, ${full} already full.` : '.'),
      err,
    )
  }

  const unlockSlot = async (slotId: string | undefined, occurrenceId: string) => {
    if (!usingLive) {
      const err = dropMemberBooking(occurrenceId)
      flash(err ? null : 'Weekly slot unlocked.', err)
      return
    }
    if (!slotId) {
      flash(null, 'This session is not part of a recurring slot.')
      return
    }
    setBusy(true)
    const { error: err, released, kept } = await studioUnlockWeeklySlot(slotId)
    setBusy(false)
    flash(
      err
        ? null
        : `Weekly slot unlocked — ${released} seat${released === 1 ? '' : 's'} released` +
          // Seats inside the transfer window stay booked and chargeable, so say so
          // rather than letting the member assume they were refunded.
          (kept ? `, ${kept} kept inside the transfer window.` : '.'),
      err,
    )
  }

  /**
   * Booking a one-off always costs extra, so the first call deliberately comes
   * back asking for confirmation instead of booking. The member then either
   * pays for it or frees up allowance by releasing a slot they already hold.
   */
  const startDropIn = async (occ: ClassOccurrence) => {
    if (!usingLive) {
      const err = bookAsMember(occ.id)
      flash(err ? null : 'Drop-in booked.', err)
      return
    }
    setBusy(true)
    const res = await studioBookSession(occ.id)
    setBusy(false)
    if (res.error) {
      flash(null, res.error)
      return
    }
    if (res.needsDropInConfirmation) {
      setDropIn({ prompt: res.needsDropInConfirmation, occ })
      return
    }
    flash('Drop-in booked.', null)
  }

  const confirmDropIn = async () => {
    if (!dropIn) return
    setBusy(true)
    const res = await studioBookSession(dropIn.occ.id, true)
    setBusy(false)
    setDropIn(null)
    flash(
      res.error ? null : `Drop-in booked — ${formatMoney(res.chargeCents)} added to your next invoice.`,
      res.error,
    )
  }

  /** Release a slot they already hold so this session is covered by the plan instead. */
  const useAllowanceInstead = async (slotIdToRelease: string) => {
    const target = dropIn?.occ.slotId
    if (!target) return
    setBusy(true)
    const released = await studioUnlockWeeklySlot(slotIdToRelease)
    const locked = released.error ? null : await studioLockWeeklySlot(target)
    setBusy(false)
    setDropIn(null)
    const err = released.error ?? locked?.error ?? null
    flash(err ? null : 'Swapped — this session now uses your included allowance.', err)
  }

  const moveLock = async (fromOccurrenceId: string, toOcc: ClassOccurrence) => {
    if (!usingLive) {
      const err = reshuffleBooking(fromOccurrenceId, toOcc.id)
      setReshuffleFrom(null)
      flash(err ? null : 'Weekly lock moved.', err)
      return
    }
    const fromSlotId = live.occurrences.find((o) => o.id === fromOccurrenceId)?.slotId
    if (!fromSlotId || !toOcc.slotId) {
      flash(null, 'Both sessions must belong to a recurring slot to move a lock.')
      return
    }
    setBusy(true)
    const unlocked = await studioUnlockWeeklySlot(fromSlotId)
    const locked = unlocked.error ? null : await studioLockWeeklySlot(toOcc.slotId)
    setBusy(false)
    setReshuffleFrom(null)
    const err = unlocked.error ?? locked?.error ?? null
    flash(err ? null : 'Weekly lock moved.', err)
  }

  return (
    <div className="fitness-page theme-gbtt">
      <AppChrome
        theme="Member booking"
        title="Weekly timetable"
        subtitle={site.heroBlurb}
        imageId="studioflow"
        backTo="/"
        backLabel="← GBTT apps"
      />

      <div className="app-sections">
      <section className="yacht-panel cal-panel app-enter app-section">
        <h2>Mon–Fri sessions</h2>
        <p className="hint">
          Weekly memberships lock recurring slots on this timetable — the same day and time every
          week. Move or unlock within your plan allowance.
        </p>
        <WeekSessionCalendar
          byDay={byDay}
          selectedId={selectedId}
          heldIds={heldIds}
          onSelect={setSelectedId}
          mode="member"
        />

        {selected && selectedType ? (
          <div className="occ-detail cal-detail">
            <ClassTypeDescription
              classType={selectedType}
              baseUrl={import.meta.env.BASE_URL}
              title={`${selectedType.name} · ${selected.dayLabel} ${selected.time}`}
            />
            <p>
              {formatSessionAttending(selected)}
              {spotsLeft(selected) === 0 ? ' · Full' : ` · ${spotsLeft(selected)} spots left`}
            </p>
            <p>
              <strong>Planned exercises:</strong>{' '}
              {sessionExercises(selected).map((e) => e.name).join(', ') || 'TBC'}
            </p>
            {member ? (
              <p>
                <strong>Classmates (opted-in):</strong>{' '}
                {visibleRosterNames(selected, member).join(', ') || 'None sharing names'}
              </p>
            ) : (
              <p className="hint">Log in below to book with a membership. Guests can still drop in.</p>
            )}

            {/* Guest drop-ins have no server-side booking path yet, so rather than
                write a booking that only exists in this browser, point them at the
                studio. */}
            {/* Guests book through a free casual account rather than a parallel
                guest path, so drop-ins get the same capacity check, roll call,
                calendar invite and billing record as anyone else. */}
            {!member && usingLive ? (
              <p className="hint">
                Dropping in? Create a free <strong>Guest / casual</strong> account below — no weekly
                subscription, just pay per session.
              </p>
            ) : null}
            {!member && !usingLive && spotsLeft(selected) > 0 ? (
              <div className="btn-row guest-book-row">
                <input
                  placeholder="Guest name"
                  value={guestName}
                  onChange={(e) => setGuestName(e.target.value)}
                  aria-label="Guest name"
                />
                <input
                  placeholder="Guest email"
                  value={guestEmail}
                  onChange={(e) => setGuestEmail(e.target.value)}
                  aria-label="Guest email"
                />
                <button
                  type="button"
                  className="btn primary"
                  onClick={() => {
                    const err = bookAsGuest(selected.id, guestName, guestEmail)
                    flash(err ? null : 'Guest booked (simulated).', err)
                  }}
                >
                  Book as guest
                </button>
              </div>
            ) : null}

            {member ? (
              <div className="btn-row">
                {selectedIsLocked ? (
                  <>
                    <button
                      type="button"
                      className="btn ghost"
                      onClick={() => {
                        setReshuffleFrom(selected.id)
                        flash('Pick another session on the calendar to move this weekly lock.', null)
                      }}
                    >
                      Move weekly lock
                    </button>
                    <button
                      type="button"
                      className="btn ghost"
                      disabled={busy}
                      onClick={() => unlockSlot(selected.slotId, selected.id)}
                    >
                      Unlock slot
                    </button>
                  </>
                ) : reshuffleFrom ? (
                  <button
                    type="button"
                    className="btn primary"
                    disabled={busy}
                    onClick={() => moveLock(reshuffleFrom, selected)}
                  >
                    Move lock here
                  </button>
                ) : (
                  <>
                    <button
                      type="button"
                      className="btn primary"
                      disabled={busy || spotsLeft(selected) === 0}
                      onClick={() => lockSlot(selected.slotId, selected.id)}
                    >
                      Lock weekly slot
                    </button>
                    <button
                      type="button"
                      className="btn ghost"
                      disabled={busy || spotsLeft(selected) === 0}
                      onClick={() => startDropIn(selected)}
                    >
                      Book one-off drop-in
                    </button>
                  </>
                )}
                {reshuffleFrom ? (
                  <button type="button" className="btn ghost" onClick={() => setReshuffleFrom(null)}>
                    Cancel move
                  </button>
                ) : null}
              </div>
            ) : null}

            {dropIn && dropIn.occ.id === selected.id ? (
              <div className="drop-in-prompt" role="alertdialog" aria-label="Confirm drop-in">
                <h3>This is an extra session</h3>
                {dropIn.prompt.allowance > 0 ? (
                  <p>
                    Your plan includes {dropIn.prompt.allowance} session
                    {dropIn.prompt.allowance === 1 ? '' : 's'} a week and you already hold{' '}
                    {dropIn.prompt.locked}. Booking this one is <strong>in addition</strong> to
                    those, charged at {formatMoney(dropIn.prompt.chargeCents)}.
                  </p>
                ) : (
                  <p>
                    Your plan has no included weekly sessions, so this is a drop-in charged at{' '}
                    {formatMoney(dropIn.prompt.chargeCents)}.
                  </p>
                )}

                <div className="btn-row">
                  <button
                    type="button"
                    className="btn primary"
                    disabled={busy}
                    onClick={confirmDropIn}
                  >
                    Book as extra · {formatMoney(dropIn.prompt.chargeCents)}
                  </button>
                  <button type="button" className="btn ghost" onClick={() => setDropIn(null)}>
                    Cancel
                  </button>
                </div>

                {/* Rather than telling them to go and deselect something, let them
                    release a slot right here and have this session take its place. */}
                {dropIn.prompt.locked > 0 && dropIn.occ.slotId ? (
                  <div className="drop-in-swap">
                    <p className="hint">
                      Or keep it within your plan by releasing a slot you already hold — this
                      session takes its place:
                    </p>
                    <ul className="drop-in-slot-list">
                      {dropIn.prompt.lockedSlotIds.map((id) => (
                        <li key={id}>
                          <span>{slotLabel(id)}</span>
                          <button
                            type="button"
                            className="btn ghost"
                            disabled={busy}
                            onClick={() => useAllowanceInstead(id)}
                          >
                            Release &amp; use here
                          </button>
                        </li>
                      ))}
                    </ul>
                  </div>
                ) : null}
              </div>
            ) : null}
          </div>
        ) : null}
      </section>

      {message ? <p className="form-success sim-banner app-section app-section--banner">{message}</p> : null}
      {error ? <p className="form-error sim-banner app-section app-section--banner">{error}</p> : null}

      <section className="yacht-panel app-enter app-section" id="login-book">
        <h2>{member ? 'Your membership' : 'Log in to book'}</h2>
        {!member ? (
          <>
            {!showRegister ? (
              <>
                <label className="field">
                  Email
                  <input value={authEmail} onChange={(e) => setAuthEmail(e.target.value)} />
                </label>
                <label className="field">
                  Password
                  <input
                    type="password"
                    value={authPassword}
                    onChange={(e) => setAuthPassword(e.target.value)}
                  />
                </label>
                <div className="btn-row">
                  <button
                    type="button"
                    className="btn primary"
                    onClick={() => {
                      const err = login(authEmail, authPassword)
                      flash(err ? null : 'Signed in — select a session on the calendar.', err)
                    }}
                  >
                    Log in to book
                  </button>
                  <button type="button" className="btn ghost" onClick={() => setShowRegister(true)}>
                    New subscription
                  </button>
                </div>
              </>
            ) : (
              <>
                <label className="field">
                  Name
                  <input value={regName} onChange={(e) => setRegName(e.target.value)} />
                </label>
                <label className="field">
                  Email
                  <input value={regEmail} onChange={(e) => setRegEmail(e.target.value)} />
                </label>
                <div className="pkg-grid">
                  {FITNESS_PLANS.filter((p) => p.classesPerWeek > 0).map((p) => (
                    <button
                      key={p.id}
                      type="button"
                      className={`pkg-card${regPlan === p.id ? ' selected' : ''}`}
                      onClick={() => setRegPlan(p.id)}
                    >
                      <strong>{p.name}</strong>
                      <span className="pkg-price">{formatPrepaid(p)}</span>
                      <p>{p.blurb}</p>
                    </button>
                  ))}
                </div>
                <label className="field">
                  Activation key
                  <input
                    value={regActivationKey}
                    onChange={(e) => setRegActivationKey(e.target.value)}
                    placeholder="From your confirmation email"
                    autoComplete="one-time-code"
                  />
                </label>
                {activationEmailSent ? (
                  <p className="form-success">
                    {formEndpointConfigured()
                      ? 'Confirmation email sent — enter the activation key above.'
                      : `Demo mode: use activation key ${DEMO_ACTIVATION_KEY}`}
                  </p>
                ) : null}
                <div className="btn-row">
                  <button type="button" className="btn ghost" onClick={() => setShowRegister(false)}>
                    Back to login
                  </button>
                  <button
                    type="button"
                    className="btn ghost"
                    onClick={async () => {
                      const result = await requestActivationEmail(regName, regEmail, regPlan)
                      if (result.ok) {
                        setActivationEmailSent(true)
                        flash(
                          result.simulated
                            ? `Demo: no email sent — use key ${DEMO_ACTIVATION_KEY}`
                            : 'Activation email sent.',
                          null,
                        )
                      } else {
                        flash(null, result.error ?? 'Could not send email.')
                      }
                    }}
                  >
                    Send activation email
                  </button>
                  <button
                    type="button"
                    className="btn primary"
                    onClick={() => {
                      const err = registerMember(regName, regEmail, regPlan, regActivationKey)
                      flash(
                        err
                          ? null
                          : 'Account created (password: demo). Accept terms, then lock your weekly slots.',
                        err,
                      )
                    }}
                  >
                    Activate &amp; create membership
                  </button>
                </div>
              </>
            )}
          </>
        ) : (
          <>
            <p>
              Signed in as <strong>{member.name}</strong> ·{' '}
              {planById(member.planId)?.name}
              {member.classesPerWeek > 0
                ? ` · ${member.weeklyLockedOccurrenceIds.length}/${member.classesPerWeek} weekly slots locked`
                : ` · ${member.creditsLeft} credits`}
            </p>
            {member.pendingPlanId ? (
              <p className="form-success">
                Plan change to <strong>{planById(member.pendingPlanId)?.name}</strong> sent to Tom —
                awaiting payment confirmation.
              </p>
            ) : null}
            <p className="hint">{site.paymentInstructions}</p>
            <label className="exercise-check">
              <input
                type="checkbox"
                checked={member.showNameToClassmates}
                onChange={(e) => {
                  setShowNameToClassmates(e.target.checked)
                  refresh()
                }}
              />
              Show my name to other subscribers in the same class
            </label>
            {!member.termsAccepted ? (
              <div className="legal-box">
                <h3>Terms &amp; waiver</h3>
                <p>{site.termsText}</p>
                <p>{site.waiverText}</p>
                <button
                  type="button"
                  className="btn primary"
                  onClick={() => {
                    acceptTerms()
                    flash('Terms accepted (simulated).', null)
                  }}
                >
                  I agree
                </button>
              </div>
            ) : null}

            <h3>Change subscription</h3>
            <p className="hint">
              Changing your plan notifies Tom so he can confirm payment logging before it takes
              effect.
            </p>
            <div className="pkg-grid">
              {FITNESS_PLANS.filter((p) => p.classesPerWeek > 0).map((p) => (
                <button
                  key={p.id}
                  type="button"
                  className={`pkg-card${member.planId === p.id ? ' selected' : ''}${member.pendingPlanId === p.id ? ' is-pending' : ''}`}
                  onClick={() => {
                    const err = requestSubscriptionChange(p.id)
                    flash(
                      err
                        ? null
                        : `Request sent to Tom for ${p.name}. Your current plan stays active until he confirms payment.`,
                      err,
                    )
                  }}
                >
                  <strong>{p.name}</strong>
                  <p>{p.blurb}</p>
                </button>
              ))}
            </div>

            <h3>Your weekly locked slots</h3>
            <ul className="held-list">
              {member.weeklyLockedOccurrenceIds.length === 0 ? (
                <li>None yet — lock a slot on the calendar (repeats every week).</li>
              ) : null}
              {member.weeklyLockedOccurrenceIds.map((id) => {
                const o = getOccurrences().find((x) => x.id === id)
                const t = o ? classTypeById(o.classTypeId) : null
                if (!o || !t) return null
                return (
                  <li key={id}>
                    {t.name} · {o.dayLabel} {o.time}
                  </li>
                )
              })}
            </ul>

            <div className="btn-row">
              <button
                type="button"
                className="btn ghost"
                onClick={() => {
                  logout()
                  flash('Signed out.', null)
                }}
              >
                Log out
              </button>
            </div>
          </>
        )}
        <p className="sync-chip">{sync.calendar}</p>
        <p className="sync-chip">{sync.firebase}</p>
      </section>
      </div>
    </div>
  )
}
